In [6]:
%pip install pandas numpy scikit-learn nltk
%pip install kagglehub

Requirement already satisfied: pandas in c:\venvs\spark_animesh\lib\site-packages (2.3.3)
Requirement already satisfied: numpy in c:\venvs\spark_animesh\lib\site-packages (2.2.6)
Requirement already satisfied: scikit-learn in c:\venvs\spark_animesh\lib\site-packages (1.7.2)
Requirement already satisfied: nltk in c:\venvs\spark_animesh\lib\site-packages (3.9.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\venvs\spark_animesh\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\venvs\spark_animesh\lib\site-packages (from pandas) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in c:\venvs\spark_animesh\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: scipy>=1.8.0 in c:\venvs\spark_animesh\lib\site-packages (from scikit-learn) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in c:\venvs\spark_animesh\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\venvs\spark_animesh\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: click in c:\venvs\spark_animesh\lib\site-packages (from nltk) (8.3.1)
Requirement already satisfied: regex>=2021.8.3 in c:\venvs\spark_animesh\lib\site-packages (from nltk) (2026.2.28)
Requirement already satisfied: tqdm in c:\venvs\spark_animesh\lib\site-packages (from nltk) (4.67.3)
Requirement already satisfied: six>=1.5 in c:\venvs\spark_animesh\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: colorama in c:\venvs\spark_animesh\lib\site-packages (from click->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting kagglehub
  Downloading kagglehub-1.0.0-py3-none-any.whl.metadata (40 kB)
Collecting kagglesdk<1.0,>=0.1.14 (from kagglehub)
  Downloading kagglesdk-0.1.16-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: packaging in c:\venvs\spark_animesh\lib\site-packages (from kagglehub) (25.0)
Requirement already satisfied: pyyaml in c:\venvs\spark_animesh\lib\site-packages (from kagglehub) (6.0.2)
Requirement already satisfied: requests in c:\venvs\spark_animesh\lib\site-packages (from kagglehub) (2.32.5)
Requirement already satisfied: tqdm in c:\venvs\spark_animesh\lib\site-packages (from kagglehub) (4.67.3)
Collecting protobuf (from kagglesdk<1.0,>=0.1.14->kagglehub)
  Downloading protobuf-7.34.0-cp310-abi3-win_amd64.whl.metadata (595 bytes)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\venvs\spark_animesh\lib\site-packages (from requests->kagglehub) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in c:\venvs\spark_animesh\lib\site-packages (from requests->kagglehub) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\venvs\spark_animesh\lib\site-packages (from requests->kagglehub) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\venvs\spark_animesh\lib\site-packages (from requests->kagglehub) (2025.8.3)
Requirement already satisfied: colorama in c:\venvs\spark_animesh\lib\site-packages (from tqdm->kagglehub) (0.4.6)
Downloading kagglehub-1.0.0-py3-none-any.whl (70 kB)
Downloading kagglesdk-0.1.16-py3-none-any.whl (160 kB)
Downloading protobuf-7.34.0-cp310-abi3-win_amd64.whl (437 kB)
Installing collected packages: protobuf, kagglesdk, kagglehub

   ---------------------------------------- 0/3 [protobuf]
   ---------------------------------------- 0/3 [protobuf]
   ---------------------------------------- 0/3 [protobuf]
   ---------------------------------------- 0/3 [protobuf]
   ---------------------------------------- 0/3 [protobuf]
   ---------------------------------------- 0/3 [protobuf]
   ---------------------------------------- 0/3 [protobuf]
   ---------------------------------------- 0/3 [protobuf]
   ---------------------------------------- 0/3 [protobuf]
   ---------------------------------------- 0/3 [protobuf]
   ---------------------------------------- 0/3 [protobuf]
   ---------------------------------------- 0/3 [protobuf]
   ---------------------------------------- 0/3 [protobuf]
   ---------------------------------------- 0/3 [protobuf]
   ---------------------------------------- 0/3 [protobuf]
   ---------------------------------------- 0/3 [protobuf]
   ---------------------------------------- 0/3 [protobuf]
   ------------- -------------------------- 1/3 [kagglesdk]
   ------------- -------------------------- 1/3 [kagglesdk]
   ------------- -------------------------- 1/3 [kagglesdk]
   ------------- -------------------------- 1/3 [kagglesdk]
   ------------- -------------------------- 1/3 [kagglesdk]
   ------------- -------------------------- 1/3 [kagglesdk]
   ------------- -------------------------- 1/3 [kagglesdk]
   ------------- -------------------------- 1/3 [kagglesdk]
   ------------- -------------------------- 1/3 [kagglesdk]
   ------------- -------------------------- 1/3 [kagglesdk]
   ------------- -------------------------- 1/3 [kagglesdk]
   ------------- -------------------------- 1/3 [kagglesdk]
   ------------- -------------------------- 1/3 [kagglesdk]
   ------------- -------------------------- 1/3 [kagglesdk]
   ------------- -------------------------- 1/3 [kagglesdk]
   ------------- -------------------------- 1/3 [kagglesdk]
   ------------- -------------------------- 1/3 [kagglesdk]
   ------------- -------------------------- 1/3 [kagglesdk]
   ------------- -------------------------- 1/3 [kagglesdk]
   ------------- -------------------------- 1/3 [kagglesdk]
   ------------- -------------------------- 1/3 [kagglesdk]
   ------------- -------------------------- 1/3 [kagglesdk]
   ------------- -------------------------- 1/3 [kagglesdk]
   ------------- -------------------------- 1/3 [kagglesdk]
   ------------- -------------------------- 1/3 [kagglesdk]
   -------------------------- ------------- 2/3 [kagglehub]
   -------------------------- ------------- 2/3 [kagglehub]
   -------------------------- ------------- 2/3 [kagglehub]
   -------------------------- ------------- 2/3 [kagglehub]
   -------------------------- ------------- 2/3 [kagglehub]
   -------------------------- ------------- 2/3 [kagglehub]
   -------------------------- ------------- 2/3 [kagglehub]
   ---------------------------------------- 3/3 [kagglehub]

Successfully installed kagglehub-1.0.0 kagglesdk-0.1.16 protobuf-7.34.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [13]:
#importing required libraries
import pandas as pd
import numpy as np
import nltk
import string

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
nltk.download('stopwords')
from kagglehub import dataset_download

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\arnap\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [ ]:
path =dataset_download("uciml/sms-spam-collection-dataset")
print(path)
import os
os.listdir(path)

['spam.csv']

In [3]:


data = pd.read_csv(path + "/spam.csv", encoding='latin-1')

data = data[['v1','v2']]
data.columns = ['label','message']

data.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
data['label'] = data['label'].map({'ham':0, 'spam':1})

data.head()

   label                                            message
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

In [5]:
X = data['message']
y = data['label']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
#Text vectorization using CountVectorizer and 
vectorizer = CountVectorizer(stop_words='english')

X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

In [ ]:
#training the machine learning model
model = MultinomialNB()

model.fit(X_train_vec, y_train)

MultinomialNB()

In [8]:
y_pred = model.predict(X_test_vec)

In [9]:
print("Accuracy:", accuracy_score(y_test, y_pred))

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

Accuracy: 0.9838565022421525

Classification Report:

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       965
           1       0.96      0.92      0.94       150

    accuracy                           0.98      1115
   macro avg       0.97      0.96      0.96      1115
weighted avg       0.98      0.98      0.98      1115

In [17]:
#Testing the model with a new email
email = ["Congratulations! You won a free lottery ticket. Click here to claim your prize."]

email_vec = vectorizer.transform(email)

prediction = model.predict(email_vec)

if prediction[0] == 1:
    print("Spam Email")
else:
    print("Not Spam (Ham)")

Spam Email

In [ ]:
#cleaning and processing the text data.
ps = PorterStemmer()

def clean_text(text):
    
    # Convert to lowercase
    text = text.lower()
    
    # Remove punctuation
    text = "".join([char for char in text if char not in string.punctuation])
    
    # Tokenization
    words = text.split()
    
    # Remove stopwords
    words = [word for word in words if word not in stopwords.words('english')]
    
    # Stemming
    words = [ps.stem(word) for word in words]
    
    # Join words
    text = " ".join(words)
    
    return text

In [15]:
def detect_spam(message):
    msg_vec = vectorizer.transform([message])
    result = model.predict(msg_vec)
    
    if result[0] == 1:
        return "Spam"
    else:
        return "Not Spam"

In [ ]:
email = input("Enter the email or message: ")
cleaned_email = clean_text(email)
print(f"Email:{email}")
print(detect_spam(cleaned_email))

Email:Congratulations! You won a free prize
Cleaned Email:congratul free prize
Spam